package Connection.Telas;


import Connection.Classes.Armazem;
import Connection.MySql.ArmazemDAO.ArmazemDAO;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    Armazem a = new Armazem();
    ArmazemDAO m = new ArmazemDAO();
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnArmazens = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblNCaminhoes = new javax.swing.JLabel();
        lblCapacidade = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldNCaminhoes = new javax.swing.JTextField();
        jTextFieldCapacidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setBackground(new java.awt.Color(34, 64, 104));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(201, 204, 223));

        jpnArmazens.setBackground(new java.awt.Color(126, 133, 176));
        jpnArmazens.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gerenciamento de Armazéns");
        jpnArmazens.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Salvar");
        btnSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar.setMaximumSize(new java.awt.Dimension(79, 25));
        btnSalvar.setMinimumSize(new java.awt.Dimension(79, 25));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jpnArmazens.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 80, -1));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpnArmazens.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        lblId.setBackground(new java.awt.Color(255, 255, 255));
        lblId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("ID:");
        jpnArmazens.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, -1));

        lblEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(255, 255, 255));
        lblEndereco.setText("Endereço:");
        jpnArmazens.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 90, -1));

        lblNCaminhoes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNCaminhoes.setForeground(new java.awt.Color(255, 255, 255));
        lblNCaminhoes.setText("Nº Caminhões:");
        jpnArmazens.add(lblNCaminhoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 90, -1));

        lblCapacidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCapacidade.setForeground(new java.awt.Color(255, 255, 255));
        lblCapacidade.setText("Capacidade:");
        jpnArmazens.add(lblCapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, -1));

        jTextFieldId.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jpnArmazens.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 90, -1));

        jTextFieldEndereco.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jpnArmazens.add(jTextFieldEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 90, -1));

        jTextFieldNCaminhoes.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jpnArmazens.add(jTextFieldNCaminhoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 91, -1));

        jTextFieldCapacidade.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jpnArmazens.add(jTextFieldCapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 91, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Endereço", "Nº Caminhões", "Capacidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setMaximumSize(new java.awt.Dimension(2147483647, 60));
        jScrollPane1.setViewportView(jTable1);

        jpnArmazens.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 620, 280));

        jTabbedPane1.addTab("Armazéns", jpnArmazens);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 620, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed
    
    private boolean validaCamposObrigatorios() {
        return !(this.jTextFieldCapacidade.getText().equals("") || this.jTextFieldEndereco.getText().equals("") ||
                this.jTextFieldId.getText().equals("") || this.jTextFieldNCaminhoes.getText().equals(""));
    }
    
    private void salvar(){
        if (validaCamposObrigatorios()){
                a.setEndereco(jTextFieldEndereco.getText());
                a.setnCaminhoes(Integer.parseInt(jTextFieldNCaminhoes.getText()));
                a.setCapacidade(Double.parseDouble(jTextFieldCapacidade.getText()));
                m.salvarDados(a);
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCapacidade;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNCaminhoes;
    private javax.swing.JPanel jpnArmazens;
    private javax.swing.JLabel lblCapacidade;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNCaminhoes;
    // End of variables declaration//GEN-END:variables
}
